export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN_ACCESS: 'FORBIDDEN_ACCESS',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NOT_CHAT_MEMBER: 'NOT_CHAT_MEMBER',
  SELF_CHAT_NOT_ALLOWED: 'SELF_CHAT_NOT_ALLOWED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  FIRESTORE_ERROR: 'FIRESTORE_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
